spring:
  profiles:
    active:
    - dev
---
spirng:
  profiles: dev
  application:
    name: microservicecloud-config-bdqn-dev
---
spirng:
  profiles: test
  application:
    name: microservicecloud-config-bdqn-test