spring:
  profiles:
   active:
   - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql:///db01
    username: root     
    password: root
    dbcp2:
     min-idle: 5        #数据库连接池最小维持连接数
     initial-size: 5    #初始化连接数
     max-total: 5       #最大连接数
     max-wait-millis: 200 #等待连接最大超时时间
mybatis:
  type-aliases-package: com.bdqn.entity
  mapper-locations:
  - classpath:mapper/**/*.xml

eureka:
  client:
   service-url:
    defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 